### ISSUE TITLE
DG check

### ISSUE THREAD

**Issue by jackgugz** [AY2122S1-CS2103T-F12-2/tp#243]
- [x] Chuan Hao
- [x] Guguz
- [x] Jerome
- [x] Nicole
- [x] Yunpeng

**Comment by Jeromesyl** [comment]
![image](https://user-images.githubusercontent.com/60766419/140538363-f92e15c6-3ff9-4f5e-87f8-78472c4b7c29.png)
Our Acknowledgement section is empty. 
I have some reuse code so I think I can add something here.

**Comment by Chang-CH** [comment]
1. We could delete the `Setting up, getting started` part
2. `#Design` puml tip is probably not meant to be there.
3. links are all incorrect. for example, Line 39 `Main has two classes called Main and MainApp.` links to the se-edu `Main` and `MainApp` etc.
4. Font size of some PUML files, e.g. delete, edit sequence diagrams, are too small. can look into editing the css to make the side margins thinner?
5. Line 110 PUML references `AddressBookParser`
6. line 119 diagram is now too small due to us having too many attributes. May have to increase width in inline `<img>` tag.
7. line 131 width too low
8. line 140 image references `JsonAdaptedTag`, should be `JsonAdaptedSkill`
9. line 187 activity diagram too small
10. Line 194, image filename not updated, should be `images/EditAllSequenceDiagram.png`.
11. Line 206, need an extra newline, GFMD is joining the lines
12. Line 221, should be `of all fields`
13. {More to be added} near the end can probably be removed
14. Private contact detail in glossary never used
15. line 563 more test cases
16. line 581  edit references delete
17. line 618-620 not updated

**Comment by jackgugz** [comment]
- [ ] shows fine on web but its shown on the md file from guthub 
![image](https://user-images.githubusercontent.com/75773252/140612275-fed6ca52-6d7a-4a6e-a822-d9c0a0ceccaa.png)
- [ ] links to all such webs are not working 
![image](https://user-images.githubusercontent.com/75773252/140612510-85af81c4-5936-4499-b6bb-3cc3c764e200.png)
- [ ] `Therefore, with the above consideration and the fact that different applicants sharing same name is relatively rare case. We decided to proceed with alternative 1.` change to `Therefore, with the above consideration and the fact that different applicants sharing same name is relatively rare case, we decided to proceed with alternative 1.`
- [ ] a new line to start from `As internship ...`
![image](https://user-images.githubusercontent.com/75773252/140612713-53aed763-8710-45e6-baba-294c2e5abac7.png)
- [ ] edit all features recommended to split into multiple graphs
- [ ] graph for edit all features to be enlarged
- [ ] sequence diagram for edit all feature is broken 
![image](https://user-images.githubusercontent.com/75773252/140612778-547fe2b7-71eb-489a-8377-b56e9e2e8ebe.png)

- [ ] a new line to start for the second `aspect` 
![image](https://user-images.githubusercontent.com/75773252/140612803-56302569-3fca-407e-bf69-75ce65a081de.png)

- [ ] delete all feature:  to be split into different paragraphs 
![image](https://user-images.githubusercontent.com/75773252/140612826-c572e7ce-a677-4f2a-9d37-5499d82ed3ac.png)

- [ ] ![image](https://user-images.githubusercontent.com/75773252/140613007-f10a2135-fb83-43a0-997d-565758dabcfa.png)
change to 
The filter mechanism is facilitated by `FilterCommandParser`. `FilterCommandParser` produces a FilterApplicantDescriptor, which in turn helps to create a `FilterCommand`.

- [ ]  
![image](https://user-images.githubusercontent.com/75773252/140613036-62416944-2965-4431-b8ac-49cb3e013806.png)
capitalise the S in `set`

- [ ] user stories to add in filter/redo/undo/editall/delete all
- [ ] use cases to add in filter 
- [ ] non functional requirements have the line "more to be added" to be deleted before final submission

**Comment by Jeromesyl** [comment]
- Line 119: References address book 
![image](https://user-images.githubusercontent.com/60766419/140687113-a3ca7bb6-e57d-4270-9e6b-ef27ad4b97e8.png)
- Line 138: References address book 
![image](https://user-images.githubusercontent.com/60766419/140687633-0287a59e-24cd-4d8a-8a63-6c2c321ab2ce.png)
