### ISSUE TITLE
Ui not reflecting state changes

### ISSUE THREAD

**Issue by yunpeng1234** [AY2122S1-CS2103T-F12-2/tp#30]
#### Steps to reproduce the issue

1.  Start program with empty save file
2. Add new candidate
3. UI remains undefined

#### What's the expected result?

- PersonDetail should update to reflect the first candidate in PersonListPanel

#### What's the actual result?

- PersonDetail does not update

#### Additional details / screenshot

**Comment by Chang-CH** [comment]
Issue occurs because:

1. PersonDetail gets information of first candidate when constructor executes
2. No event listeners are hooked to update PersonDetail on PersonListPanel updates

Starting with a non empty save file shows details of first candidate, which means the constructor is receiving data as intended.
